# Generated by Django 4.2.6 on 2023-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Please enter the post title')),
                ('content', models.TextField(verbose_name='Please enter the post text')),
                ('createdDate', models.DateField()),
            ],
        ),
    ]
